name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Please search existing issues before opening a new one to avoid duplicates.**
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`.
      placeholder: "e.g. go1.23.0 darwin/arm64"
  - type: input
    id: os-arch
    attributes:
      label: OS and architecture
      placeholder: "e.g. macOS 15.0, arm64"
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. Do '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any relevant log output or error messages.
      render: shell
  - type: input
    id: version
    attributes:
      label: xp-tracker version or commit SHA
      placeholder: "e.g. v0.1.0 or abc1234"
